github.com:
    users:
        sh4dqwx:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: sh4dqwx
