github.com:
    users:
        sh4dqwx:
            oauth_token: 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
    git_protocol: https
    user: sh4dqwx
    oauth_token: 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
